### ISSUE TITLE
Seems to require --delete-conflicting-outputs option

### ISSUE THREAD

**Issue by ilyannn** [minikin/flutter-web-demo#2]
Only works with `flutter packages pub run build_runner build --delete-conflicting-outputs`
Possible reason: [this issue](https://github.com/dart-lang/build/issues/1214)

**To Reproduce**
Trying the `flutter packages pub global run webdev build`:

```
➜  flutter-web-demo git:(master) ✗ flutter packages pub global run webdev build
[WARNING] Configuring `build_vm_compilers:entrypoint` in target `flutter_web_demo:flutter_web_demo` but this is not a known Builder
[INFO] Found 2 declared outputs which already exist on disk. This is likely because the`.dart_tool/build` folder was deleted, or you are submitting [SEVERE] Conflicting outputs were detected and the build is unable to prompt for permission to remove them. These outputs must be removed manually or the build can be run with `--delete-conflicting-outputs`. The outputs are: lib/models/serializers.g.dart
[INFO] Unhandled exception:
Bad state: Unable to start build daemon.
#0      _handleDaemonStartup (package:build_daemon/client.dart:52:5)
<asynchronous suspension>
#1      BuildDaemonClient.connect (package:build_daemon/client.dart:142:11)
<asynchronous suspension>
#2      connectClient (package:webdev/src/daemon_client.dart:17:23)
#3      BuildCommand.run (package:webdev/src/command/build_command.dart:56:26)
<asynchronous suspension>
#4      CommandRunner.runCommand (package:args/command_runner.dart:196:27)
<asynchronous suspension>
#5      _CommandRunner.runCommand (package:webdev/src/webdev_command_runner.dart:38:24)
<asynchronous suspension>
#6      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:111:29)
#7      new Future.sync (dart:async/future.dart:224:31)
#8      CommandRunner.run (package:args/command_runner.dart:111:11)
#9      run (package:webdev/src/webdev_command_runner.dart:19:56)
#10     main (file:///Users/in/Library/flutter/.pub-cache/hosted/pub.dartlang.org/webdev-2.0.5/bin/webdev.dart:17:22)
<asynchronous suspension>
#11     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:298:32)
#12     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
pub finished with exit code 255
```

**Info:**
```
➜  flutter-web-demo git:(master) ✗ flutter --version
Flutter 1.5.4-hotfix.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7a4c33425d (3 weeks ago) • 2019-04-29 11:05:24 -0700
Engine • revision 52c7a1e849
Tools • Dart 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)
```

**Comment by ilyannn** [comment]
Actually not reproducible anymore.

**Comment by minikin** [comment]
Thanks, @ilyannn  for the report. I've just added an additional step to README.
